name: traceoff_mobile
description: TraceOff Mobile App - Share links without trackers
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.1

  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # URL Handling
  url_launcher: ^6.2.2

  # Share & Clipboard
  share_plus: ^7.2.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
