// Auto-generated by scripts/generate-build-info.js
// Do not edit manually.
export const BUILD_INFO = {
  commit: "369139d9af2e4a61be5648e9803e63a96591281f",
  short: "369139d",
  builtAt: "2025-12-04T03:41:15.169Z",
};
