name: Test and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CI: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node for root + server
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Match npm version (11.4.2) & verify
        run: |
          npm install -g npm@11.4.2
          node -v
          npm -v

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Run server tests
        run: |
          cd server
          npm test

      - name: Run server linting
        run: |
          cd server
          npm run lint

      # Tooling needed for Android + Web builds
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.3
          channel: stable
          cache: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup environment file
        run: cp server/.env.example mobile/.env

      - name: Install Flutter dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Run Flutter tests
        run: |
          cd mobile
          flutter test

      - name: Run Flutter analysis
        run: |
          cd mobile
          flutter analyze

      - name: Build Flutter app (Android debug)
        run: |
          cd mobile
          flutter build apk --debug

      - name: Build Flutter app (Web release)
        run: |
          cd mobile
          flutter build web --release
