name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-server:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
      - name: Match npm version (11.4.2) & verify
        run: |
          npm install -g npm@11.4.2
          node -v
          npm -v
      - name: Install, lint, test, build
        working-directory: server
        run: |
          npm ci
          npm run lint
          npm test
          npm run build
      - name: Upload server build
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: server/dist

  test-mobile:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.3
          channel: stable
          cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: android-actions/setup-android@v3
      - run: flutter --version
      - name: Setup environment file
        run: cp server/.env.example mobile/.env
      - working-directory: mobile
        run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

  test-integration:
    runs-on: ubuntu-latest
    needs: [test-server, test-mobile]
    timeout-minutes: 20
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
      - name: Match npm version (11.4.2) & verify
        run: |
          npm install -g npm@11.4.2
          node -v
          npm -v
      - name: Install & start server
        working-directory: server
        run: |
          npm ci
          npm run build
          nohup npm start &
          sleep 5
      - name: Run integration tests (API endpoints) with retry
        run: |
          for i in {1..10}; do
            if curl -fsS http://localhost:3000/health; then break; fi
            sleep 2
          done
          curl -fsS -X POST http://localhost:3000/api/clean \
            -H "Content-Type: application/json" \
            -d '{"url":"https://example.co
